FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y --no-install-recommends build-essential cmake
RUN apt-get install -y --no-install-recommends ruby libqt4-dev libqt4-sql-mysql\
    libmysqlclient-dev libacpi-dev libudev-dev

VOLUME /startkladde
